apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-worker-ansible2.14
  labels:
    name: locust-worker
spec:
  replicas: 4
  selector:
    matchLabels:
      app: locust-worker
  template:
    metadata:
      labels:
        app: locust-worker
    spec:
      containers:
        - name: locust-worker
          image: quay.io/rhcloudperfscale/tower-analytics:latest
          env:
            - name: LOCUST_MODE
              value: worker
            - name: LOCUST_MASTER_URL
              value: locust-master
            - name: TARGET_HOST
              value: https://cloud.stage.redhat.com

          imagePullPolicy: Always
          resources:
            requests:
              cpu: 500m
              memory: 800Mi

      imagePullSecrets:
        - name: rhcloudperfscale-puller-pull-secret